### ISSUE TITLE
Clarification needed regarding Base URL

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [eid-login/eid-login-nextcloud#4] opened 2021-09-24 12:53 UTC
Hello,

i've tested the Plugin, here are some results.

Apparently the Document Root has to point to the Base URL. In many configuration there's a URL path 'www.domain.com/nextcloud', but a successful authentication will push you to the base url www.domain.com, disregarding the /nextcloud path. Still, you get a valid token and can access the nextcloud environment visiting www.domain.com/nextcloud .
If there's no way to set the correct path in the plugin this should be pointed out in the admin documentation.

Mixed results authenticating with german ID-Card via Personalausweis-App using a USB ReinerSCT RFID Comfort Reader. The process did not recognize the ID-Card every time, just sporadically, but working flawlessly using the NFC-Reader from my iPhone. At the same time i had no problem reading out my data towards Governikus to display stored data in the same session.
But there's too much interference on my side from other sources like antivirus H Abstraction, PC/SC Configuration and Smartcard Services that i wont dive deeper into debugging it, it's merely for your information.

**Comment by 7118path** [comment] 2021-09-24 12:56
Thank you for your feedback! I will have a look into the document root issue.

**Comment by 7118path** [comment] 2021-09-28 08:16
This issue should be fixed with 604e54541315067e9dfeb429a048b0484b31b2c9

**Closed as completed by 7118path** 2021-09-28 08:16 UTC

**Comment by FlyinFistOfJuda** [comment] 2021-10-02 14:16
Thanks, that worked.
Still, non-EID registered users get a notification bell information regarding _eID-Login available_ pointing to 
`<button data-v-0629c5a5="" data-type="WEB" data-href="/settings/user/security" class="action-button pull-right">`
This link leads to a 404-error.
In the users settings menu, the link for the security options refer to
`<a href="/cloud/settings/user/security">`
'cloud' is the nextcloud path.

**Comment by 7118path** [comment] 2021-10-04 09:02
Thank you very much for this feedback. The issue is fixed in 86c0bcb025789b6bb882fda8442a0a5d68d43467
