### ISSUE TITLE
Nextcloud Hub II (23.0.0) connecting eID with German Perso not possible.

### ISSUE THREAD

**Issue by GereonW** [eid-login/eid-login-nextcloud#6] opened 2021-12-10 20:22 UTC
I am using "AusweisApp2" and "skidentity" to Authenticate and I get no error whatsoever in the process until i am getting redirected to the nextcloud settings page where this error is shown:

```error
Erstellung der eID-Verknüpfung fehlgeschlagen! Bitte stellen Sie sicher, dass die genutzte eID-Karte gültig ist.
```
Protokoll app shows this:

```log
[PHP] Fehler: Required parameter $reqId follows optional parameter $nameIdValueReq at /var/www/html/custom_apps/eidlogin/dep/OneLogin/Saml2/Auth.php#735

GET /index.phpogin/eid/createeid?requesttoken=Cys2ORIPqH%2BYMhYy%2F1%2BfOK4uuyIJZUEihEU1b%2BJxe3g%3D%3AQ3p4CkN55wjZS2ZGzjv2WZxrlBRxDAZ0wzVdPMkZOgg%3D
from ********** by ********** at 2021-12-10T19:58:51+00:00
```

I hope somone could help me fixing this.

**Comment by 7118path** [comment] 2021-12-13 08:16
This problem is caused by PHP 8 and we try to fix it in an upcoming release. Thank you for reporting it!
@ecmrauh FYI

**Comment by 7118path** [comment] 2021-12-14 07:55
This should be fixed with https://github.com/eid-login/eid-login-nextcloud/releases/tag/1.0.7

**Closed as completed by 7118path** 2021-12-14 07:55 UTC

**Comment by GereonW** [comment] 2021-12-14 18:03
Perfect. I've just updated it, now it works properly.
