### ISSUE TITLE
Warning in logs - Icon of notification is not an absolute URL

### ISSUE THREAD

**Issue by AndiDoe** [eid-login/eid-login-nextcloud#19] opened 2024-11-27 23:26 UTC
Icon of notification is not an absolute URL and does not work in mobile and desktop clients [app: eidlogin, subject: eidlogin_setup_done]

Steps: eID App is activated.
Create new User/Account 
Login with new created Account.

Wait for it, when the App notifies the user to setup eID.

Best wishes

**Comment by ecmrauh** [comment] 2024-11-29 14:33
Thanks for the hint! The issue is fixed in https://github.com/eid-login/eid-login-nextcloud/commit/d6649f2ba08fca4b389dc7c51f0f893fabc55810.

**Closed as completed by ecmrauh** 2024-11-29 14:33 UTC
